---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redis
  install:
    timeout: 20m
    createNamespace: true
    remediation:
      retries: 3
  interval: 1m0s
  releaseName: redis
  targetNamespace: redis

